server:
  port: ${server-port} #9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/JavaMonolithicExampleDb
    url: ${url} #jdbc:postgresql://10.88.0.28:5432/JavaMonolithicExampleDb
    username: ${user} #postgres
    password: ${password} #root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true